def generate_bounty_report(title: str, severity: str, summary: str, steps_to_reproduce: str, impact: str, recommendation: str) -> str:
    report_template = f"""
# {title}

**Severity:** {severity}


---


##Summary
{summary}


---


## Steps to Reproduce
{steps_to_reproduce}


---


## Impact
{impact}


---


## Recommendation
{recommendation}


---
*Generated by Project Orchestra*
"""
    return report_template.strip()
